[advisories]
ignore = []

[bans]
multiple-versions = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]

[licenses]
allow = ["MIT", "Apache-2.0"]

[[licenses.exceptions]]
allow = ["0BSD"]
name = "yikes-intenum"
